
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 02 07:55:27 VET 2012
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int AND = 27;
  public static final int READ = 8;
  public static final int NE = 25;
  public static final int OVER = 18;
  public static final int LT = 14;
  public static final int ELSE = 4;
  public static final int PLUS = 15;
  public static final int INT = 29;
  public static final int OR = 28;
  public static final int RPAREN = 20;
  public static final int THEN = 3;
  public static final int SEMI = 21;
  public static final int END = 5;
  public static final int IF = 2;
  public static final int GT = 24;
  public static final int LPAREN = 19;
  public static final int LE = 22;
  public static final int WRITE = 9;
  public static final int ID = 10;
  public static final int NUM = 11;
  public static final int EOF = 0;
  public static final int GE = 23;
  public static final int MINUS = 16;
  public static final int MAINB = 26;
  public static final int error = 1;
  public static final int UNTIL = 7;
  public static final int ASSIGN = 12;
  public static final int EQ = 13;
  public static final int REPEAT = 6;
}

